# Generated by Django 3.2.6 on 2021-08-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_arbitrage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(default=None, max_length=20, null=True, verbose_name='Биржа')),
                ('last_update', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
            ],
            options={
                'db_table': 'exchange_update',
            },
        ),
    ]
