# Generated by Django 3.1.1 on 2021-04-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_arbitrage', '0002_auto_20210411_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=80, null=True, verbose_name='Имя')),
                ('binance_key', models.CharField(default=None, max_length=80, null=True, verbose_name='Binance Key')),
                ('binance_secret', models.CharField(default=None, max_length=80, null=True, verbose_name='Binance Secret')),
                ('bittrex_key', models.CharField(default=None, max_length=80, null=True, verbose_name='Bittrex Key')),
                ('bittrex_secret', models.CharField(default=None, max_length=80, null=True, verbose_name='Bittrex Secret')),
                ('poloniex_key', models.CharField(default=None, max_length=80, null=True, verbose_name='Poloniex Key')),
                ('poloniex_secret', models.CharField(default=None, max_length=80, null=True, verbose_name='Poloniex Secret')),
                ('hitbtc_key', models.CharField(default=None, max_length=80, null=True, verbose_name='HitBTC Key')),
                ('hitbtc_secret', models.CharField(default=None, max_length=80, null=True, verbose_name='HitBTC Secret')),
                ('kucoin_key', models.CharField(default=None, max_length=80, null=True, verbose_name='Kucoin Key')),
                ('kucoin_secret', models.CharField(default=None, max_length=80, null=True, verbose_name='Kucoin Secret')),
                ('kraken_key', models.CharField(default=None, max_length=80, null=True, verbose_name='Kraken Key')),
                ('kraken_secret', models.CharField(default=None, max_length=80, null=True, verbose_name='Kraken Secret')),
                ('huobi_key', models.CharField(default=None, max_length=80, null=True, verbose_name='Huobi Key')),
                ('huobi_secret', models.CharField(default=None, max_length=80, null=True, verbose_name='Huobi Secret')),
                ('okex_key', models.CharField(default=None, max_length=80, null=True, verbose_name='OKex Key')),
                ('okex_secret', models.CharField(default=None, max_length=80, null=True, verbose_name='OKex Secret')),
                ('gateio_key', models.CharField(default=None, max_length=80, null=True, verbose_name='Gate.io Key')),
                ('gateio_secret', models.CharField(default=None, max_length=80, null=True, verbose_name='Gate.io Secret')),
                ('coinex_key', models.CharField(default=None, max_length=80, null=True, verbose_name='Coinex Key')),
                ('coinex_secret', models.CharField(default=None, max_length=80, null=True, verbose_name='Coinex Secret')),
                ('bitz_key', models.CharField(default=None, max_length=80, null=True, verbose_name='Bit-Z Key')),
                ('bitz_secret', models.CharField(default=None, max_length=80, null=True, verbose_name='Bit-Z Secret')),
                ('bibox_key', models.CharField(default=None, max_length=80, null=True, verbose_name='Bibox Key')),
                ('bibox_secret', models.CharField(default=None, max_length=80, null=True, verbose_name='Bibox Secret')),
            ],
        ),
    ]
