# Generated by Django 3.1.1 on 2021-05-14 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ca_arbitrage', '0004_auto_20210513_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_time', models.DateField(auto_now_add=True, verbose_name='Дата оплаты')),
                ('money', models.FloatField(default=0, verbose_name='Оплата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payments_name', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_payments',
            },
        ),
        migrations.CreateModel(
            name='UsersAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_pay_time', models.DateField(auto_now=True, verbose_name='Дата последней оплаты')),
                ('days', models.IntegerField(default=0, verbose_name='Кол-во оплаченных дней')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account_name', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_account',
            },
        ),
    ]
