# Generated by Django 3.1.1 on 2021-08-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_arbitrage', '0005_usersaccount_userspayments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibox',
            name='volume',
            field=models.FloatField(default=None, null=True, verbose_name='Объем рынка'),
        ),
        migrations.AlterField(
            model_name='binance',
            name='volume',
            field=models.FloatField(default=None, null=True, verbose_name='Объем рынка'),
        ),
        migrations.AlterField(
            model_name='bittrex',
            name='volume',
            field=models.FloatField(default=None, null=True, verbose_name='Объем рынка'),
        ),
        migrations.AlterField(
            model_name='bitz',
            name='volume',
            field=models.FloatField(default=None, null=True, verbose_name='Объем рынка'),
        ),
        migrations.AlterField(
            model_name='coinex',
            name='volume',
            field=models.FloatField(default=None, null=True, verbose_name='Объем рынка'),
        ),
        migrations.AlterField(
            model_name='gateio',
            name='volume',
            field=models.FloatField(default=None, null=True, verbose_name='Объем рынка'),
        ),
        migrations.AlterField(
            model_name='hitbtc',
            name='volume',
            field=models.FloatField(default=None, null=True, verbose_name='Объем рынка'),
        ),
        migrations.AlterField(
            model_name='huobi',
            name='volume',
            field=models.FloatField(default=None, null=True, verbose_name='Объем рынка'),
        ),
        migrations.AlterField(
            model_name='kraken',
            name='volume',
            field=models.FloatField(default=None, null=True, verbose_name='Объем рынка'),
        ),
        migrations.AlterField(
            model_name='kucoin',
            name='volume',
            field=models.FloatField(default=None, null=True, verbose_name='Объем рынка'),
        ),
        migrations.AlterField(
            model_name='okex',
            name='volume',
            field=models.FloatField(default=None, null=True, verbose_name='Объем рынка'),
        ),
        migrations.AlterField(
            model_name='poloniex',
            name='volume',
            field=models.FloatField(default=None, null=True, verbose_name='Объем рынка'),
        ),
        migrations.AlterField(
            model_name='userskeys',
            name='telegram',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='Telegram'),
        ),
    ]
