# Generated by Django 3.1.1 on 2021-08-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_arbitrage', '0005_usersaccount_userspayments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskeys',
            name='telegram',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='Telegram'),
        ),
    ]
