# Generated by Django 3.1.1 on 2021-04-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_arbitrage', '0005_userkeys_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkeys',
            name='bibox_key',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='Bibox Key'),
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='bibox_secret',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='Bibox Secret'),
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='binance_key',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='Binance Key'),
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='binance_secret',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='Binance Secret'),
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='bittrex_key',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='Bittrex Key'),
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='bittrex_secret',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='Bittrex Secret'),
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='bitz_key',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='Bit-Z Key'),
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='bitz_secret',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='Bit-Z Secret'),
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='coinex_key',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='Coinex Key'),
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='coinex_secret',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='Coinex Secret'),
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='gateio_key',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='Gate.io Key'),
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='gateio_secret',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='Gate.io Secret'),
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='hitbtc_key',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='HitBTC Key'),
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='hitbtc_secret',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='HitBTC Secret'),
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='huobi_key',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='Huobi Key'),
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='huobi_secret',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='Huobi Secret'),
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='kraken_key',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='Kraken Key'),
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='kraken_secret',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='Kraken Secret'),
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='kucoin_key',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='Kucoin Key'),
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='kucoin_secret',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='Kucoin Secret'),
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='okex_key',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='OKex Key'),
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='okex_secret',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='OKex Secret'),
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='poloniex_key',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='Poloniex Key'),
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='poloniex_secret',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='Poloniex Secret'),
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='telegram',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Telegram'),
        ),
    ]
