# Generated by Django 3.1.1 on 2021-04-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_arbitrage', '0006_auto_20210425_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkeys',
            name='poloniex_secret',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Poloniex Secret'),
        ),
    ]
