# Generated by Django 3.1.1 on 2021-05-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_arbitrage', '0007_auto_20210426_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkeys',
            name='kucoin_password',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='Kucoin Password'),
        ),
        migrations.AddField(
            model_name='userkeys',
            name='okex_password',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='OKex Password'),
        ),
    ]
