# Generated by Django 3.1.1 on 2021-05-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_arbitrage', '0008_auto_20210501_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkeys',
            name='kraken_key',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Kraken Key'),
        ),
    ]
